# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: floatingdrivers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='floatingdrivers.proto',
  package='memory',
  serialized_pb=_b('\n\x15\x66loatingdrivers.proto\x12\x06memory\"0\n\x12\x46loatingDriverType\x12\x0c\n\x04Name\x18\x01 \x02(\t\x12\x0c\n\x04Path\x18\x02 \x02(\t\">\n\x08rootType\x12\x32\n\x0e\x46loatingDriver\x18\x01 \x03(\x0b\x32\x1a.memory.FloatingDriverType')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLOATINGDRIVERTYPE = _descriptor.Descriptor(
  name='FloatingDriverType',
  full_name='memory.FloatingDriverType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='memory.FloatingDriverType.Name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Path', full_name='memory.FloatingDriverType.Path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=81,
)


_ROOTTYPE = _descriptor.Descriptor(
  name='rootType',
  full_name='memory.rootType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FloatingDriver', full_name='memory.rootType.FloatingDriver', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=145,
)

_ROOTTYPE.fields_by_name['FloatingDriver'].message_type = _FLOATINGDRIVERTYPE
DESCRIPTOR.message_types_by_name['FloatingDriverType'] = _FLOATINGDRIVERTYPE
DESCRIPTOR.message_types_by_name['rootType'] = _ROOTTYPE

FloatingDriverType = _reflection.GeneratedProtocolMessageType('FloatingDriverType', (_message.Message,), dict(
  DESCRIPTOR = _FLOATINGDRIVERTYPE,
  __module__ = 'floatingdrivers_pb2'
  # @@protoc_insertion_point(class_scope:memory.FloatingDriverType)
  ))
_sym_db.RegisterMessage(FloatingDriverType)

rootType = _reflection.GeneratedProtocolMessageType('rootType', (_message.Message,), dict(
  DESCRIPTOR = _ROOTTYPE,
  __module__ = 'floatingdrivers_pb2'
  # @@protoc_insertion_point(class_scope:memory.rootType)
  ))
_sym_db.RegisterMessage(rootType)


# @@protoc_insertion_point(module_scope)
