# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addatastructs/processors.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addatastructs/processors.proto',
  package='memory',
  serialized_pb='\n\x1e\x61\x64\x64\x61tastructs/processors.proto\x12\x06memory\"9\n\x0fUnspecifiedType\x12\x16\n\x0e\x62\x61seObjectType\x18\x01 \x02(\t\x12\x0e\n\x06object\x18\x02 \x02(\x0c\"\xa5\x01\n\x0cIDTEntryType\x12\x15\n\rInterruptGate\x18\x01 \x01(\t\x12\x10\n\x08TaskGate\x18\x02 \x01(\t\x12\x13\n\x0bInvalidGate\x18\x03 \x01(\t\x12\x10\n\x08TrapGate\x18\x04 \x01(\t\x12\x0f\n\x07\x41\x64\x64ress\x18\x05 \x02(\x04\x12\x0e\n\x06Module\x18\x06 \x01(\t\x12\x10\n\x08Selector\x18\x07 \x02(\x05\x12\x12\n\nAttributes\x18\x08 \x02(\x05\"F\n\x1cInterruptDescriptorTableType\x12&\n\x08IDTEntry\x18\x01 \x03(\x0b\x32\x14.memory.IDTEntryType\"c\n\rProcessorType\x12\n\n\x02ID\x18\x01 \x02(\x05\x12\x46\n\x18InterruptDescriptorTable\x18\x02 \x02(\x0b\x32$.memory.InterruptDescriptorTableType\"4\n\x08rootType\x12(\n\tProcessor\x18\x01 \x03(\x0b\x32\x15.memory.ProcessorType')




_UNSPECIFIEDTYPE = _descriptor.Descriptor(
  name='UnspecifiedType',
  full_name='memory.UnspecifiedType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseObjectType', full_name='memory.UnspecifiedType.baseObjectType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object', full_name='memory.UnspecifiedType.object', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=99,
)


_IDTENTRYTYPE = _descriptor.Descriptor(
  name='IDTEntryType',
  full_name='memory.IDTEntryType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='InterruptGate', full_name='memory.IDTEntryType.InterruptGate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TaskGate', full_name='memory.IDTEntryType.TaskGate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InvalidGate', full_name='memory.IDTEntryType.InvalidGate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TrapGate', full_name='memory.IDTEntryType.TrapGate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Address', full_name='memory.IDTEntryType.Address', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Module', full_name='memory.IDTEntryType.Module', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Selector', full_name='memory.IDTEntryType.Selector', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Attributes', full_name='memory.IDTEntryType.Attributes', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=267,
)


_INTERRUPTDESCRIPTORTABLETYPE = _descriptor.Descriptor(
  name='InterruptDescriptorTableType',
  full_name='memory.InterruptDescriptorTableType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IDTEntry', full_name='memory.InterruptDescriptorTableType.IDTEntry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=269,
  serialized_end=339,
)


_PROCESSORTYPE = _descriptor.Descriptor(
  name='ProcessorType',
  full_name='memory.ProcessorType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='memory.ProcessorType.ID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InterruptDescriptorTable', full_name='memory.ProcessorType.InterruptDescriptorTable', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=341,
  serialized_end=440,
)


_ROOTTYPE = _descriptor.Descriptor(
  name='rootType',
  full_name='memory.rootType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Processor', full_name='memory.rootType.Processor', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=442,
  serialized_end=494,
)

_INTERRUPTDESCRIPTORTABLETYPE.fields_by_name['IDTEntry'].message_type = _IDTENTRYTYPE
_PROCESSORTYPE.fields_by_name['InterruptDescriptorTable'].message_type = _INTERRUPTDESCRIPTORTABLETYPE
_ROOTTYPE.fields_by_name['Processor'].message_type = _PROCESSORTYPE
DESCRIPTOR.message_types_by_name['UnspecifiedType'] = _UNSPECIFIEDTYPE
DESCRIPTOR.message_types_by_name['IDTEntryType'] = _IDTENTRYTYPE
DESCRIPTOR.message_types_by_name['InterruptDescriptorTableType'] = _INTERRUPTDESCRIPTORTABLETYPE
DESCRIPTOR.message_types_by_name['ProcessorType'] = _PROCESSORTYPE
DESCRIPTOR.message_types_by_name['rootType'] = _ROOTTYPE

class UnspecifiedType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNSPECIFIEDTYPE

  # @@protoc_insertion_point(class_scope:memory.UnspecifiedType)

class IDTEntryType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IDTENTRYTYPE

  # @@protoc_insertion_point(class_scope:memory.IDTEntryType)

class InterruptDescriptorTableType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTERRUPTDESCRIPTORTABLETYPE

  # @@protoc_insertion_point(class_scope:memory.InterruptDescriptorTableType)

class ProcessorType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROCESSORTYPE

  # @@protoc_insertion_point(class_scope:memory.ProcessorType)

class rootType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROOTTYPE

  # @@protoc_insertion_point(class_scope:memory.rootType)


# @@protoc_insertion_point(module_scope)
