# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addatastructs/device.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addatastructs/device.proto',
  package='memory',
  serialized_pb='\n\x1a\x61\x64\x64\x61tastructs/device.proto\x12\x06memory\"9\n\x0fUnspecifiedType\x12\x16\n\x0e\x62\x61seObjectType\x18\x01 \x02(\t\x12\x0e\n\x06object\x18\x02 \x02(\x0c\"\x96\x01\n\nDeviceType\x12\x0c\n\x04Name\x18\x01 \x02(\t\x12\x1a\n\x12\x44\x65viceObj_Location\x18\x02 \x02(\x04\x12\x1a\n\x12\x44riverObj_Location\x18\x03 \x02(\x04\x12\x1e\n\x16NextDeviceObj_Location\x18\x04 \x02(\x04\x12\"\n\x1a\x41ttachedDeviceObj_Location\x18\x05 \x02(\x04\".\n\x08rootType\x12\"\n\x06\x44\x65vice\x18\x01 \x03(\x0b\x32\x12.memory.DeviceType')




_UNSPECIFIEDTYPE = _descriptor.Descriptor(
  name='UnspecifiedType',
  full_name='memory.UnspecifiedType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseObjectType', full_name='memory.UnspecifiedType.baseObjectType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object', full_name='memory.UnspecifiedType.object', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=95,
)


_DEVICETYPE = _descriptor.Descriptor(
  name='DeviceType',
  full_name='memory.DeviceType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='memory.DeviceType.Name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeviceObj_Location', full_name='memory.DeviceType.DeviceObj_Location', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DriverObj_Location', full_name='memory.DeviceType.DriverObj_Location', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NextDeviceObj_Location', full_name='memory.DeviceType.NextDeviceObj_Location', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AttachedDeviceObj_Location', full_name='memory.DeviceType.AttachedDeviceObj_Location', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=248,
)


_ROOTTYPE = _descriptor.Descriptor(
  name='rootType',
  full_name='memory.rootType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Device', full_name='memory.rootType.Device', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=250,
  serialized_end=296,
)

_ROOTTYPE.fields_by_name['Device'].message_type = _DEVICETYPE
DESCRIPTOR.message_types_by_name['UnspecifiedType'] = _UNSPECIFIEDTYPE
DESCRIPTOR.message_types_by_name['DeviceType'] = _DEVICETYPE
DESCRIPTOR.message_types_by_name['rootType'] = _ROOTTYPE

class UnspecifiedType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNSPECIFIEDTYPE

  # @@protoc_insertion_point(class_scope:memory.UnspecifiedType)

class DeviceType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICETYPE

  # @@protoc_insertion_point(class_scope:memory.DeviceType)

class rootType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROOTTYPE

  # @@protoc_insertion_point(class_scope:memory.rootType)


# @@protoc_insertion_point(module_scope)
