# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addatastructs/module.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addatastructs/module.proto',
  package='memory',
  serialized_pb='\n\x1a\x61\x64\x64\x61tastructs/module.proto\x12\x06memory\"9\n\x0fUnspecifiedType\x12\x16\n\x0e\x62\x61seObjectType\x18\x01 \x02(\t\x12\x0e\n\x06object\x18\x02 \x02(\x0c\"s\n\nModuleType\x12\x0c\n\x04Name\x18\x01 \x02(\t\x12\x0c\n\x04Path\x18\x02 \x02(\t\x12\x0f\n\x07\x41\x64\x64ress\x18\x03 \x02(\x04\x12\x12\n\nEntryPoint\x18\x04 \x02(\x04\x12\x0c\n\x04Size\x18\x05 \x02(\x05\x12\x16\n\x0eresultitemtype\x18\x06 \x01(\x05\".\n\x08rootType\x12\"\n\x06Module\x18\x01 \x03(\x0b\x32\x12.memory.ModuleType')




_UNSPECIFIEDTYPE = _descriptor.Descriptor(
  name='UnspecifiedType',
  full_name='memory.UnspecifiedType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseObjectType', full_name='memory.UnspecifiedType.baseObjectType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object', full_name='memory.UnspecifiedType.object', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=95,
)


_MODULETYPE = _descriptor.Descriptor(
  name='ModuleType',
  full_name='memory.ModuleType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='memory.ModuleType.Name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Path', full_name='memory.ModuleType.Path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Address', full_name='memory.ModuleType.Address', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EntryPoint', full_name='memory.ModuleType.EntryPoint', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Size', full_name='memory.ModuleType.Size', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resultitemtype', full_name='memory.ModuleType.resultitemtype', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=212,
)


_ROOTTYPE = _descriptor.Descriptor(
  name='rootType',
  full_name='memory.rootType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Module', full_name='memory.rootType.Module', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=214,
  serialized_end=260,
)

_ROOTTYPE.fields_by_name['Module'].message_type = _MODULETYPE
DESCRIPTOR.message_types_by_name['UnspecifiedType'] = _UNSPECIFIEDTYPE
DESCRIPTOR.message_types_by_name['ModuleType'] = _MODULETYPE
DESCRIPTOR.message_types_by_name['rootType'] = _ROOTTYPE

class UnspecifiedType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNSPECIFIEDTYPE

  # @@protoc_insertion_point(class_scope:memory.UnspecifiedType)

class ModuleType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODULETYPE

  # @@protoc_insertion_point(class_scope:memory.ModuleType)

class rootType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROOTTYPE

  # @@protoc_insertion_point(class_scope:memory.rootType)


# @@protoc_insertion_point(module_scope)
